# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
# apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

# [templates]
# defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit && compinit'

[plugins.p10k]
github = "romkatv/powerlevel10k"
use = ["*10k.zsh-theme"]

[plugins.syntax-highlight]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.git]
github = "sorin-ionescu/prezto"
use = ["/init.zsh", "/modules/git/init.zsh", "/modules/osx/init.zsh", "/modules/archive/init.zsh"]

[plugins.fzf]
github = "junegunn/fzf"
use = ["shell/completion.zsh"]

[plugins.fzf.hooks]
post = "source <(fzf --zsh | sed -e '/zmodload/s/perl/perl_off/' -e '/selected/s/fc -rl/fc -irl/')"

[plugins.docker-cli]
github = "docker/cli"
use = ["contrib/completion/zsh/_docker"]
