#!/bin/bash

# based on/using http://stackoverflow.com/questions/21378569 and
# https://gist.github.com/martijnvermaat/8070533

# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
            # X11UseLocalhost=yes
            echo add unix:`echo $DISPLAY |
                cut -c11-` $proto $cookie
    else
            # X11UseLocalhost=no
            echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
